import java.util.Map;

public class LanguageTable {
    public static Map<Character, Integer> alphabetTable = Map.ofEntries(
            Map.entry('А', 1),
            Map.entry('Б', 2),
            Map.entry('В', 3),
            Map.entry('Г', 4),
            Map.entry('Д', 5),
            Map.entry('Е', 6),
            Map.entry('Ё', 7),
            Map.entry('Ж', 8),
            Map.entry('З', 9),
            Map.entry('И', 10),
            Map.entry('Й', 11),
            Map.entry('К', 12),
            Map.entry('Л', 13),
            Map.entry('М', 14),
            Map.entry('Н', 15),
            Map.entry('О', 16),
            Map.entry('П', 17),
            Map.entry('Р', 18),
            Map.entry('С', 19),
            Map.entry('Т', 20),
            Map.entry('У', 21),
            Map.entry('Ф', 22),
            Map.entry('Х', 23),
            Map.entry('Ц', 24),
            Map.entry('Ч', 25),
            Map.entry('Ш', 26),
            Map.entry('Щ', 27),
            Map.entry('Ъ', 28),
            Map.entry('Ы', 29),
            Map.entry('Ь', 30),
            Map.entry('Э', 31),
            Map.entry('Ю', 32),
            Map.entry('Я', 33),
            Map.entry(',', 34),
            Map.entry('.', 35),
            Map.entry('!', 36),
            Map.entry('?', 37)
    );

    public static Map<Integer, Character> numberTable = Map.ofEntries(
            Map.entry(1, 'А'),
            Map.entry(2, 'Б'),
            Map.entry(3, 'В'),
            Map.entry(4, 'Г'),
            Map.entry(5, 'Д'),
            Map.entry(6, 'Е'),
            Map.entry(7, 'Ё'),
            Map.entry(8, 'Ж'),
            Map.entry(9, 'З'),
            Map.entry(10, 'И'),
            Map.entry(11, 'Й'),
            Map.entry(12, 'К'),
            Map.entry(13, 'Л'),
            Map.entry(14, 'М'),
            Map.entry(15, 'Н'),
            Map.entry(16, 'О'),
            Map.entry(17, 'П'),
            Map.entry(18, 'Р'),
            Map.entry(19, 'С'),
            Map.entry(20, 'Т'),
            Map.entry(21, 'У'),
            Map.entry(22, 'Ф'),
            Map.entry(23, 'Х'),
            Map.entry(24, 'Ц'),
            Map.entry(25, 'Ч'),
            Map.entry(26, 'Ш'),
            Map.entry(27, 'Щ'),
            Map.entry(28, 'Ъ'),
            Map.entry(29, 'Ы'),
            Map.entry(30, 'Ь'),
            Map.entry(31, 'Э'),
            Map.entry(32, 'Ю'),
            Map.entry(33, 'Я')
    );
}
